// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run against the direct (non-pooled) connection —
    // Supabase's pgbouncer pooler doesn't support the DDL/prepared
    // statements the schema engine needs.
    url: process.env["DIRECT_URL"],
  },
});
